name: Windows LiteManager

on:

  workflow_dispatch:
jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl -L -o "Downloads.bat" "https://gitlab.com/chamod12/1m_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to Lite Manager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
